version: '3'
services:
  backend:
    container_name: 'traffic-backend'
    build: ./backend
    restart: always
    ports:
      - 8000:8000
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - RPC_HOST_LIST=${RPC_HOST_LIST}
    links:
      - detector_1
      - detector_2
    volumes:
      - video-in-volume:/mnt/video-in
      - video-out-volume:/mnt/video-out

  detector_1:
    container_name: 'traffic-detector-1'
    build: 
      context: ./video-detector
    restart: always
    volumes:
      - video-in-volume:/app/video-detector/videos
      - video-out-volume:/app/video-detector/output
    
  detector_2:
    container_name: 'traffic-detector-2'
    build: 
      context: ./video-detector
    restart: always
    volumes:
      - video-in-volume:/app/video-detector/videos
      - video-out-volume:/app/video-detector/output

volumes:
  video-out-volume: 
  video-in-volume: