apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      volumes:
      - name: video-storage
        persistentVolumeClaim:
          claimName: pvc-video-storage
      containers:
      - name: backend-container
        image: lawrence910426/traffic-backend
        volumeMounts:
          - name: video-storage
            mountPath: /mnt
      restartPolicy: Always