apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-video-storage
spec:
  storageClassName: ceph-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi